spring.application.name=demo
# Tells Spring Boot to stop searching for a local Windows Docker installation
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:mysql://localhost:3306/walletdb
spring.datasource.username=root
spring.datasource.password=sql@123

spring.jpa.hibernate.ddl-auto=update
//rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.jpa.show-sql=true
